-- liquibase formatted sql

-- changeset karybekov:1
CREATE TABLE IF NOT EXISTS animal_shelter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255),
    work_schedule VARCHAR(255)
    name VARCHAR(100)
    photo BIGINT REFERENCES photo(id)
);

CREATE TABLE IF NOT EXISTS pet_owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone INT
);

CREATE TABLE IF NOT EXISTS pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick VARCHAR(255),
    animal_shelter_id BIGINT REFERENCES animal_shelter(id)
    pet_owner_id BIGINT REFERENCES pet_owner(id)
);

CREATE TABLE IF NOT EXISTS owner_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet VARCHAR(255),
    well_being VARCHAR(255),
    behaviour_change VARCHAR(255),
    pet_owner_id BIGINT REFERENCES pet_owner(id)
);

CREATE TABLE IF NOT EXISTS bot_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    message TEXT,
    notification_date_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS volunteer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR(255),
    file_size BIGINT,
    media_type VARCHAR(255),
    data BYTEA,
    animal_shelter_id BIGINT REFERENCES animal_shelter(id),
    pet_owner_id BIGINT REFERENCES pet_owner(id)
    CONSTRAINT check_one_empty CHECK (
        (animal_shelter_id IS NULL AND pet_owner_id IS NOT NULL) OR
        (animal_shelter_id IS NOT NULL AND pet_owner_id IS NULL)
    )
);


