-- liquibase formatted sql

-- changeset karybekov:1
CREATE TABLE IF NOT EXISTS animal_shelter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    media_type VARCHAR(255),
    data BYTEA
);

CREATE TABLE IF NOT EXISTS pet_owner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone INT
);

CREATE TABLE IF NOT EXISTS pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nick VARCHAR(255),
    pet_owner_id INT REFERENCES pet_owner(id)
);

CREATE TABLE IF NOT EXISTS owner_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diet VARCHAR(255),
    well_being VARCHAR(255),
    behaviour_change VARCHAR(255),
    file_path VARCHAR(255),
    file_size BIGINT,
    media_type VARCHAR(255),
    data BYTEA,
    pet_id INT REFERENCES pet(id)
);

CREATE TABLE IF NOT EXISTS bot_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    message TEXT,
    notification_date_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS volunteer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(100)
);

-- changeset karybekov:2
ALTER TABLE animal_shelter ADD COLUMN work_schedule VARCHAR(255);

-- changeset karybekov:3
DROP TABLE animal_shelter;

CREATE TABLE IF NOT EXISTS animal_shelter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    address VARCHAR(255),
    work_schedule VARCHAR(255)
);

-- changeset karybekov:4
ALTER TABLE pet ADD COLUMN animal_shelter_id BIGINT REFERENCES animal_shelter(id);

